/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as OurApproachRouteImport } from './routes/our-approach'
import { Route as ExecutiveSearchRouteImport } from './routes/executive-search'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OurApproachRoute = OurApproachRouteImport.update({
  id: '/our-approach',
  path: '/our-approach',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveSearchRoute = ExecutiveSearchRouteImport.update({
  id: '/executive-search',
  path: '/executive-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/executive-search': typeof ExecutiveSearchRoute
  '/our-approach': typeof OurApproachRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/executive-search': typeof ExecutiveSearchRoute
  '/our-approach': typeof OurApproachRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/executive-search': typeof ExecutiveSearchRoute
  '/our-approach': typeof OurApproachRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact'
    | '/executive-search'
    | '/our-approach'
    | '/services'
    | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact'
    | '/executive-search'
    | '/our-approach'
    | '/services'
    | '/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact'
    | '/executive-search'
    | '/our-approach'
    | '/services'
    | '/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactRoute: typeof ContactRoute
  ExecutiveSearchRoute: typeof ExecutiveSearchRoute
  OurApproachRoute: typeof OurApproachRoute
  ServicesRoute: typeof ServicesRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-approach': {
      id: '/our-approach'
      path: '/our-approach'
      fullPath: '/our-approach'
      preLoaderRoute: typeof OurApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-search': {
      id: '/executive-search'
      path: '/executive-search'
      fullPath: '/executive-search'
      preLoaderRoute: typeof ExecutiveSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactRoute: ContactRoute,
  ExecutiveSearchRoute: ExecutiveSearchRoute,
  OurApproachRoute: OurApproachRoute,
  ServicesRoute: ServicesRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
